name: "Setup and build inngest"
description: "Sets up Node, installs dependencies, and builds the inngest package."
inputs:
  working-directory:  # id of input
    description: 'The directory to run the action in.'
    required: false
    default: '.'
  build:
    description: 'Whether the build step should be run.'
    required: false
    default: true
runs:
  using: composite
  steps:
    - uses: volta-cli/action@v4

    - uses: pnpm/action-setup@v2
      with:
        run_install: false

    - name: Get pnpm store directory
      id: pnpm-cache
      shell: bash
      run: |
        echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

    - uses: actions/cache@v3
      name: Setup pnpm cache
      with:
        path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
        key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-pnpm-store-

    - run: volta install node
      shell: bash

    - run: volta install @antfu/ni
      shell: bash

    - name: Install dependencies
      run: pnpm install
      shell: bash
      working-directory: ${{ inputs.working-directory }}/packages/inngest

    - name: Build
      if: ${{ inputs.build == 'true' }}
      run: pnpm run build
      shell: bash
      working-directory: ${{ inputs.working-directory }}/packages/inngest
