name: "Setup and build inngest"
description: "Sets up Bun, installs dependencies, and builds the inngest package."
inputs:
  working-directory:  # id of input
    description: 'The directory to run the action in.'
    required: false
    default: '.'
  build:
    description: 'Whether the build step should be run.'
    required: false
    default: true
runs:
  using: composite
  steps:
    - uses: oven-sh/setup-bun@v1

    - run: bun install -g @antfu/ni
      shell: bash

    - name: Install dependencies
      run: bun install
      shell: bash
      working-directory: ${{ inputs.working-directory }}/packages/inngest

    - name: Build
      if: ${{ inputs.build == 'true' }}
      run: bun run build
      shell: bash
      working-directory: ${{ inputs.working-directory }}/packages/inngest
